version: "3.5"
services:
  digikam:
    image: linuxserver/digikam
    container_name: digikam
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./app/config:/config
    ports:
      - 3000:3000 #optional
    restart: unless-stopped