version: "3.5"
services:
  pixapop:
    image: linuxserver/pixapop
    container_name: pixapop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - APP_USERNAME=admin #optional
      - APP_PASSWORD=admin #optional
    volumes:
      - ./app/config:/config
      - ./app/photos:/photos
    ports:
      - 9381:80
    restart: unless-stopped