version: "3.5"
services:
  doublecommander:
    image: linuxserver/doublecommander
    container_name: doublecommander
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./app/config:/config
      - ./app/data:/data
    ports:
      - 3000:3000
    restart: unless-stopped